language: node_js
node_js:
  - '14.15.5'
os: windows

install:
  - npm install newman

script:
  - node_modules/.bin/newman run tests3/Frontend_Calls.postman3_collection.json -e tests3/aliyun_staging.postman3_environment.json

